#!/usr/bin/env bash
#
# Build .env.production from .env.local, applying the production overrides.
#
#   ./scripts/makeProdEnv.sh
#
# Hand-typing forty secrets into nano over SSH at 2am is how a launch goes wrong:
# one transposed character in JWT_SECRET logs everybody out, and one wrong
# character in DATABASE_URL looks like "the database is down".
#
# So generate the file locally, where the values are known-good, and copy it up.
#
# This NEVER prints a secret. It reports key names and whether they are set.
# Both this file's output and .env.local are covered by `.env*` in .gitignore.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=".env.local"
OUT=".env.production"
DOMAIN="https://kamathchessacademy.com"

[ -f "$SRC" ] || { echo "ABORT: $SRC not found." >&2; exit 1; }

if [ -f "$OUT" ]; then
  read -r -p "$OUT exists. Overwrite? [y/N] " reply
  [ "$reply" = "y" ] || { echo "Left alone."; exit 0; }
fi

# Keys the production file sets itself; drop any copy coming from .env.local.
OVERRIDDEN="NODE_ENV NEXT_PUBLIC_APP_URL NEXT_PUBLIC_SOCKET_URL QUEUE_REDIS_URL EMAIL_FROM EMAIL_REPLY_TO"
# Keys that are local-only or belong to services not deployed.
DROPPED="NEO4J_URI NEO4J_USER NEO4J_PASSWORD OLLAMA_BASE_URL OLLAMA_MODEL"

{
  echo "# Generated by scripts/makeProdEnv.sh — DO NOT COMMIT."
  echo "# Keep a copy in your password manager: this file exists nowhere else."
  echo

  # Carry everything across except the keys we set or drop below. Comments and
  # blank lines come too, so the file stays readable.
  awk -v overridden="$OVERRIDDEN" -v dropped="$DROPPED" '
    BEGIN { split(overridden " " dropped, skip, " "); for (i in skip) drop[skip[i]] = 1 }
    /^[[:space:]]*#/ { print; next }
    /^[[:space:]]*$/ { print; next }
    {
      key = $0; sub(/[[:space:]]*=.*/, "", key); gsub(/^[[:space:]]+/, "", key)
      if (key in drop) next
      print
    }
  ' "$SRC"

  echo
  echo "# ---- production overrides (set by makeProdEnv.sh) ----"
  echo "NODE_ENV=production"
  echo "NEXT_PUBLIC_APP_URL=$DOMAIN"
  echo "NEXT_PUBLIC_SOCKET_URL=$DOMAIN"
  # The Redis service inside docker-compose, not Upstash. Without this, jobs run
  # inline and a restart mid-job leaves the row stuck in `processing` forever.
  echo "QUEUE_REDIS_URL=redis://redis:6379"
  echo 'EMAIL_FROM="Kamath Chess Academy <noreply@kamathchessacademy.com>"'
  echo 'EMAIL_REPLY_TO="kamathchessacademy@gmail.com"'
} > "$OUT"

chmod 600 "$OUT"

echo "Wrote $OUT"
echo

# --- Report, without revealing anything -------------------------------------
missing=0
echo "Required keys:"
# NOT listed: NEXT_PUBLIC_SUPABASE_URL / _ANON_KEY / SUPABASE_SERVICE_ROLE_KEY.
# Grepped 2026-09-12: no file in src/, server.mjs or prisma/ reads any of them, and
# @supabase/* is not a dependency. This app reaches Postgres through Prisma and
# `pg` directly and does not use Supabase Auth or Storage. DEPLOYMENT.md used to
# call them required, which sends you hunting for keys that change nothing.
for key in JWT_SECRET JWT_REFRESH_SECRET DATABASE_URL DIRECT_URL \
           UPSTASH_REDIS_REST_URL UPSTASH_REDIS_REST_TOKEN \
           LICHESS_API_TOKEN RESEND_API_KEY AI_PROVIDER; do
  if grep -qE "^[[:space:]]*${key}=.+" "$OUT"; then
    printf "  ✓ %s\n" "$key"
  else
    printf "  ✗ %s  — MISSING\n" "$key"
    missing=$((missing + 1))
  fi
done

echo
echo "Set by this script:"
grep -E '^(NODE_ENV|NEXT_PUBLIC_APP_URL|NEXT_PUBLIC_SOCKET_URL|QUEUE_REDIS_URL|EMAIL_FROM|EMAIL_REPLY_TO)=' "$OUT" | sed 's/^/  /'

# A pooled runtime URL and a direct migration URL are different ports on purpose.
if grep -qE '^DATABASE_URL=.*:5432' "$OUT"; then
  echo
  echo "  ⚠️  DATABASE_URL uses port 5432 (direct). Runtime wants the POOLED 6543 URL"
  echo "      with ?pgbouncer=true; 5432 belongs in DIRECT_URL."
fi
if grep -qE '^DIRECT_URL=.*:6543' "$OUT"; then
  echo
  echo "  ⚠️  DIRECT_URL uses the 6543 pooler. Migrations hang on it — use 5432."
fi
if grep -qE '^RAZORPAY_(KEY_ID|KEY_SECRET|WEBHOOK_SECRET)=.+' "$OUT"; then
  echo
  echo "  ℹ️  Razorpay keys present — checkout will be LIVE. Remove all three to stay free."
fi

echo
if [ "$missing" -gt 0 ]; then
  echo "❌ $missing required key(s) missing. Fix .env.local and re-run." >&2
  exit 1
fi
echo "✅ Ready. Copy it to the server once you have the IP:"
echo "     scp .env.production root@YOUR_SERVER_IP:/opt/kca/.env.production"
